sudo: false
language: python
python:
  - "3.4"
  - "3.5"
install: pip install .
script: py.test
env:
  - secure: "xnQOI92GSzYOfLCKvIn68L36rvy0Dhfu8oxzG9KkmrfqjpGocdA6Plm/BxqLyTRjbkOyv0uEJUtJGfrrlltR2IinPbsUx0bcyJdKDDXQ6+yYghFyCvg+VdsJCHzBvEOb+Sf62HnHsuSND2wpS6SGbpETtnaN1Wm0eEWW5YtWcrZEaJA2DcIIkaT8fIoy2u8kQxOZwmcTrf+oElVejjaXUnps98dQNd+vcygNGE1Fo/G3MmcUg8NNwLmZNnvzAFM1kup0UqgLy6QAyF7zfgGNtKf2I0E+oPM2z3j0fFHOXDwnSQLdGj55HK4OonqI4GkvjwNg84stXAVZA50F6iTlwJnDGsds7/0WOD1d84KAb6XRzhaCJSugfpcWQdNIfYFSacm9JkFJMngYsth4rR+PNZV8nyI+iYS8oXZfnmDK4uKT0DYkz+Ouae+jkrdEtBLPEtTE1HkiNWKPZQj/lPU+hLxg5dm0W/ClnPdS4Lzvx+OTwQH+uiue+6tHNi1ELcd/M9HtQVAmEZikHxi9FI59LYcuF9HMPw9f1epHZ41v2PyNGg00A+KSjuQImXqdenZRiEqeAAP84z5SJjjKx6uI+3nsf0ZK2j0J28A9iHOgdQrlJoJhc4HV7lKinLBwn6jZwKXhpVRYFRdv4kz2hJuTLwZHc8n3/pGVc8eFwjmIGbY="
