sudo: false
language: python
python:
  - "3.4"
  - "3.5"
install: pip install .
script: py.test
env:
  - secure: "e459mVJF0tG98wXyV5oHgNbu6cty/7PopwpsbesaEmpiOt2saZiD/zTjYqLZRn4N7Dzwytly0bGNJ3NXzt39ny96htGoJnCwm/r8b1PcvcKxxJ/C+hbtwcLcPT0JsuXYCHnFKihgoR/rnlcNcPu9QvVzn1fS1iuCpjduYy+anZ1Bjir/TKwOqsSBWas1VWlispZkBqSYfQOK9TvBYc1PrAV0a0eakxfXQpueNqJUWYu/qUD7zrsNK8lhRCZ1oPUQIQnxulyVjzz+s77yz0xNQcEdEkf8MDI9stmviS54N0bAbnFnLZxrBGMJCy42CwecMN/V2hbfdc9gbcbqknP+4vGNS4a1zyTGNp1T8Ek4PU+r9wikTGm5QBMAkeaODINBQpbC5Ynwx812ZoirdtlIj0M0wejLIGkulCiJ/2e16Pj5jCJUjVOFndHp32MneueVDgEHIR+xhYvacbveviF6LfPEn5shRfxO1YWMse0IjizEPXN6NMsujkUpmvJOcWud6+rZ4n7Pq9sbzrLSHR5+Tf0UYcFysALAJpYpUgdfxLs3WL2fIKUc8pA2GqLOcGftQpNMV08CFpQpFZLkcWE8tyrW3P5ya2yUKzySLHmmgHBn9JcO+HjLKTgV8F8dbpXXCOMRWswB6fH2UDLpXkm4ymaYXlT6s1xyeOX/ipju25I="
