sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
install: pip install -U pytest pytest-runner
script: python setup.py ptr
env:
  global:
    - ASYNC_TEST_TIMEOUT=20
    - secure: "e459mVJF0tG98wXyV5oHgNbu6cty/7PopwpsbesaEmpiOt2saZiD/zTjYqLZRn4N7Dzwytly0bGNJ3NXzt39ny96htGoJnCwm/r8b1PcvcKxxJ/C+hbtwcLcPT0JsuXYCHnFKihgoR/rnlcNcPu9QvVzn1fS1iuCpjduYy+anZ1Bjir/TKwOqsSBWas1VWlispZkBqSYfQOK9TvBYc1PrAV0a0eakxfXQpueNqJUWYu/qUD7zrsNK8lhRCZ1oPUQIQnxulyVjzz+s77yz0xNQcEdEkf8MDI9stmviS54N0bAbnFnLZxrBGMJCy42CwecMN/V2hbfdc9gbcbqknP+4vGNS4a1zyTGNp1T8Ek4PU+r9wikTGm5QBMAkeaODINBQpbC5Ynwx812ZoirdtlIj0M0wejLIGkulCiJ/2e16Pj5jCJUjVOFndHp32MneueVDgEHIR+xhYvacbveviF6LfPEn5shRfxO1YWMse0IjizEPXN6NMsujkUpmvJOcWud6+rZ4n7Pq9sbzrLSHR5+Tf0UYcFysALAJpYpUgdfxLs3WL2fIKUc8pA2GqLOcGftQpNMV08CFpQpFZLkcWE8tyrW3P5ya2yUKzySLHmmgHBn9JcO+HjLKTgV8F8dbpXXCOMRWswB6fH2UDLpXkm4ymaYXlT6s1xyeOX/ipju25I="
    - secure: "gikPNqM4jWs2HWVQ1onPkgO7xgFVHqHN/SxR9nUstjsY92I7b1sj7gU+f/7dxEwEQXyNXNHPQtOe2QxcbI25eIJjbPl2S+59rcdTjsOLXeHR8XTOg22OPk5+G/wyFFUmOKwKMIup/4DZQHXaUh0CoEpOEfYXNZNZDXYhtJaqSBRnrsqIA9zaUDcBdrKXsZzQ8i5v5+U2duF2EPYCGmxiCvSd741YbsCqbsPCvwcOiovF/bf1lUD7e4QLtT8ZClMwC5OcNG1Yvg3i6+YPQNhynGmQyzE8SSuFlbfNuXt3ZfqL+07DAXPv4Knz2UKW7eQtnI6iVWu882zCt0HBZ1LUzSvCF/tzJjKVl0+VvkfDO8Yv47HaSE/Q2Hq65oPQaAn/kE5QCnauZmIa+scGFQ9BRRgJWNYjPzXGogf8lHXGN+y2N0DQCW8dDN0xbR9XF9DzW2xXkGfeAHF3lIENvREfrm7fTfNN5+yw0WTUw4+gQiazdshCGhUABALUWk5aEqtIeDOWOgx3j3JYAS66fyKovnZS8rzyEjqftCNBwmUKnRutYw1gk00OCAAiaiz0jk+6LBj+EiH2Y8SxfhobnbJ6rdU5UpFv4Q/J7fXg4OfgMYt83rdYb/in0wFH9IKpPXlIYCgrSVoZBQBEIBclBYiWtFRwlLAdcGdK8Z4SHbuOeG0="
